server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:txdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "hibernate.format_sql": true

# service endpoints it will call
account:
  service:
    base-url: http://localhost:8082

payments:
  service:
    base-url: http://localhost:8084

notification:
  service:
    base-url: http://localhost:8085


