server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:notifydb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "hibernate.format_sql": true
